name: Static Code Analysis

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Specifies the JDK distribution

      - name: Install Checkstyle
        run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.18.1/checkstyle-10.18.1-all.jar -O checkstyle.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml $(find . -name "*.java")
